# Set path
path=(
  /usr/local/anaconda/bin
  /usr/local/anaconda/python.app/Contents/MacOS
  /usr/local/anaconda/envs/python3/bin
  $HOME/bin
  $HOME/.cabal/bin
  /usr/texbin
  /usr/local/{bin,sbin}
  /usr/local/gocode/bin
  $path
)

export GOPATH=/usr/local/gocode
