# Set path
path=(
  /Users/sglyon/anaconda3/bin
  /Users/sglyon/src/julia/julia/usr/bin
  $HOME/bin
  $HOME/.cabal/bin
  $HOME/.cargo/bin
  /usr/local/{bin,sbin}
  /usr/texbin
  $HOME/gocode/bin
  $HOME/google-cloud-sdk/bin
  $path
)

export GOPATH=$HOME/gocode
export JULIA_EDITOR=subl
export LT_HOME=$HOME/src/LightTable/deploy

export GRB_LICENSE_FILE=$HOME/src/gurobi.lic

export DYLD_LIBRARY_PATH=/opt/NAG/clmi623dgl/lib

# Add GHC 7.8.3 to the PATH, via http://ghcformacosx.github.io/
export GHC_DOT_APP="/Users/sglyon/src/haskell/ghc-7.8.3.app"
if [ -d "$GHC_DOT_APP" ]; then
    export PATH="${HOME}/.cabal/bin:${GHC_DOT_APP}/Contents/bin:${PATH}"
fi

# so gcloud doesn't complain about python 3
export CLOUDSDK_PYTHON=/Users/sglyon/anaconda/bin/python

# alias julia4="/usr/local/julia/usr/bin/julia"
alias pip2="/usr/local/anaconda2/bin/pip"
alias conda2="/usr/local/anaconda2/bin/conda"
alias ipython2="/Users/sglyon/anaconda3/envs/py2/bin/ipython"
alias ipypy="/usr/local/share/pypy/ipython"
alias gco='git checkout'

alias matlab="/Applications/MATLAB_R2015b.app/bin/matlab -nodesktop -nosplash"

# use hub instead of git
eval "$(hub alias -s)"

# export CLASSPATH=/opt/ParallelColt/parallelcolt-0.9.4.jar:/opt/colt/lib/colt.jar:/opt/colt/lib/concurrent.jar:$CLASSPATH

export RSTUDIO_WHICH_R=/Users/sglyon/anaconda3/bin/R
export ATOM_REPOS_HOME=$HOME/src/atom
export EDITOR="atom"
export RUBYMOTION_ANDROID_SDK=/Users/sglyon/.rubymotion-android/sdk
export RUBYMOTION_ANDROID_NDK=/Users/sglyon/.rubymotion-android/ndk

export PATH="/usr/local/heroku/bin:$PATH"
export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
source ~/.rvm/scripts/rvm
