;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	mouse-buffer-menu
	org-beginning-of-line
	org-dblock-update
	))

(setq mc/cmds-to-run-once
      '(
	mouse-set-region
	org-backward-sentence
	org-self-insert-command
	save-some-buffers
	))
