;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        ess-eval-region-or-function-or-paragraph-and-step
        ess-smart-comma
        mouse-buffer-menu
        org-beginning-of-line
        org-dblock-update
        suspend-frame
        ))

(setq mc/cmds-to-run-once
      '(
        mouse-set-region
        org-backward-sentence
        org-insert-link
        org-self-insert-command
        save-some-buffers
        ))
